server:
  port: ":8080"

redis:
  # Single node configuration (uncomment to use)
  addr: "localhost:6379"
  # Cluster configuration (uncomment to use)
  # cluster:
  #   nodes:
  #     - "uat.redis.03.ykf.mth:7000"
  #     - "uat.redis.02.ykf.mth:7000"
  #     - "uat.redis.01.ykf.mth:7000"
  #     - "uat.redis.03.ykf.mth:7001"
  #     - "uat.redis.02.ykf.mth:7001"
  #     - "uat.redis.01.ykf.mth:7001"
  
  # Common settings for both single node and cluster
  password: ""
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

limiter:
  default_rate: 10
  default_burst: 50

log:
  level: "info"
  format: "json"
  output: "file"
  file_path: "logs"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true 