server:
  port: ":8080"

redis:
  addr: "single-redis.meditrusthealth.com:6378"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

limiter:
  default_rate: 10   # 默认每秒令牌生成速率
  default_burst: 50  # 默认桶容量

log:
  level: "info"        # 日志级别: debug, info, warn, error
  format: "json"       # 日志格式: json, console
  output: "file"       # 输出位置: stdout, file
  file_path: "logs"    # 日志文件路径
  max_size: 100        # 单个日志文件最大大小(MB)
  max_backups: 10      # 最大备份文件数
  max_age: 30          # 日志文件保留天数
  compress: true       # 是否压缩旧日志文件 